DEFAULT_PORTFOLIOS = [
    "Optum Insight",
    "ETIPS",
    "CDO",
]

DEFAULT_SUB_PORTFOLIOS = [
    "Provider",
    "Tech Data",
    "Payer",
    "SGS",
]

DEFAULT_TOWERS = [
    "Payment Integrity",
    "OIT OA PAYER ENGINEERING",
    "COB",
    "Subrogation",
    "PAY COB",
    "PRINT & COMMUNICATION",
    "OIT Payer Cross-Capabilities",
    "OIT HIN",
    "OIT ENABLEMENT PLATFORM",
    "Provider Enablement",
    "Analytics",
    "Platform Services",
    "Payer Risk & Quality",
    "Patient Engage",
    "Payer Data engineering",
    "Optum Insight",
    "EBX-TIBCO",
    "OIPDI-Engineering",
    "OIT OPI DATA ENGINEERING",
    "OIT OPI CLINICAL",
    "PAYER RISK AND QUALITY SOL",
    "OIT VALUE ENABLEMENT LEGACY",
    "OIT PAY COB",
    "Enterprise Tools",
    "IT Risk Management",
    "Tech Data Products - Legacy",
    "REVENUE CYCLE BACK END",
    "eFR Legacy",
    "TECH & DATA",
    "EFR Billing",
    "Assurance",
    "Provider",
    "Optum Match",
    "Unity Catalog Migration",
    "InterQual",
    "Tech Data products",
    "State Govt",
    "RPA",
    "OLS Catch and Fetch",
    "Assurance Test Automation",
    "UHG Modernization",
    "RTS Mobile App",
    "Acuity",
]

DEFAULT_BUSINESS_UNITS = [
    "New",
    "Replacement",
    "FPP/SOW/RFP",
]

DEFAULT_LOCATIONS = [
    "Onshore",
    "Offshore",
    "Nearshore",
]

DEFAULT_SUB_LOCATIONS = [
    "India",
    "USA",
    "Mexico",
]

DEFAULT_REQUIREMENT_TYPES = [
    "T&M",
    "FPP",
]

DEFAULT_JOB_ROLES = [
    "Business Analyst",
    "Integration Coordinator",
    "Integration Lead/Manager",
    "Product Owner",
    "IT Project Manager",
    "Scrum Master",
    "Change Management",
    "Technology Product Manager",
    "Data Analyst",
    "Data Engineer",
    "DBA",
    "Database Support Engineer",
    "Enterprise Resource Planning",
    "IT Systems Management Analyst",
    "Conversational Voice Design",
    "Database Development",
    "Network Engineer",
    "Network Operations Engineer",
    "Voice/Telecom Data Engineer",
    "Quality Assurance/Engineering",
    "IT Security Analyst",
    "Security Engineer",
    "Cloud Security Engineer",
    "Helpdesk/Deskside",
    "O365 Engineer",
    "IT Warehouse Analyst",
    "Customer Care Product/Application Support",
    "Architect",
    "Cloud Operations",
    "Full Stack Engineer",
    "System Analyst",
    "Application Developer - Niche",
    "IT Web Developer",
    "AI/ML Engineers - Gen AI",
]

DEFAULT_SKILL_CATEGORIES = [
    "Java Full stack",
    "Java Developer",
    "Dot Net Full stack",
    "Don Net Developer",
    "Data Engineer",
    "AWS Engineer",
    "AI/ML Engineer",
    "Azure Engineer",
    "Functional QA",
    "Automation QA",
    "Scrum Master",
    "Big Data Engineer",
    "Business Analyst",
    "Technical Product Owner",
    "UI Engineer",
    "Data Analyst",
    "NLP Data Scientist",
    "Azure Administrator",
    "SRE Engineer",
    "Data Scientist",
    "Python Developer",
    "Architect",
]

DEFAULT_JOB_POSTING_STATUSES = [
    "Submitted",
    "Halted",
    "Hold",
    "Closed",
]

DEFAULT_CUSTOMER_CIOS = [
    "Charette, Francois",
]

DEFAULT_CUSTOMER_LEADERS = [
    "Blyakhman Alex",
    "Mansour Adnan",
    "Viljoen Andre",
    "Nagnur Milind",
    "Howard Aaron",
    "Mullapudi Konda",
    "Junus Rudy",
    "Gott Peter",
]

DEFAULT_CUSTOMER_VPS = [
    "Mehta VS",
    "Keeney Richard",
    "Shetty Sarosh",
    "Pollakampalli Narendra",
    "Swanagon John",
    "Viljoen Andre",
    "Howard Aaron",
    "Dreher Jeffery",
    "Babu Suprigya",
    "Sagar Arun",
    "Olson Erik",
    "Mansour Adnan",
    "Junus Rudy",
    "Gupta Achana",
    "Martinson Kurt",
    "Jaiswal, Rohit",
    "Hoake Michael",
    "Bhagyashree Joshi",
    "Smith Jim",
    "Gott Peter",
    "Raya Madhuri",
    "Deruyck John D",
    "Pozzi Zachary",
    "Banaei Mehnoush",
    "Dwivedi Sourabh",
    "Konda Mullapudi",
    "Mullapudi Konda",
    "Potter Brian C",
    "Ginal steve",
    "Blyakhman Alex",
    "Harvey Jeffrey",
]

DEFAULT_CUSTOMER_SENIOR_DIRECTORS = [
    "Dhulipalla Anusha",
    "Pollakampalli Narendra",
    "Ganji Muralidhar",
    "Aldentifier Christina",
    "Keeney Richard",
    "Treichel Joseph D",
    "CHI SUN",
    "Patil Natraj",
    "Tyrell Krystal",
    "Compton Chris",
    "Chandra Vipin",
    "MACKAY SCOTT",
    "Sagar Arun",
    "BORCHELT PAUL",
    "Ramanathan Karthick",
    "Anusha Dhulipala",
    "Thorat Prasad",
    "Selvam Santhosh",
    "Sharma Ayush",
    "Joshi Bhagyashree",
    "Sharma Sudeep",
    "Babu Suprigya",
    "Thomas Jacob Vijay",
    "Mehta Vs",
    "Selvam Santhosh K",
    "Jaiswal Rohit",
    "Hoake Michael",
    "Hunur Neha N",
    "Srinivasan Ramu",
    "Raicea Cristain",
    "Ramu Srinivasan",
    "Dam Sajal",
    "Mann Amandeep",
    "North Brian",
    "Bagade Vivek Kumar",
    "Deasy Brian",
    "Raya Madhuri",
    "Deruyck John D",
    "Mackay Scott",
    "Wagh Rakesh G",
    "Moore Janice L",
    "Banaei Mehnoush",
    "Dwivedi Sourabh",
    "Philpot Vernon",
    "Casey Khan",
    "Sudeep Sharma",
    "Kollavajjala Deepak",
    "Kumar Karunesh",
    "Khurana Sumit",
    "Polakampalli Narendra",
]

DEFAULT_CUSTOMER_DIRECTORS = [
    "Srinivasan Ramu",
    "KAZMIERCZAK PAUL",
    "Subbaraj Ravisankar",
    "Rajarathinam Senthil",
    "Aldentifier Christina",
    "Patil Natraj",
    "Mckinney Trey",
    "CHI SUN",
    "Makowski Joseph W",
    "Tyrell Krystal",
    "Chandra Vipin",
    "MACKAY SCOTT",
    "Janze Leonard",
    "Sharma Rishi",
    "BORCHELT PAUL",
    "Ramanathan Karthick",
    "Olstad Paul",
    "Kovvuri Lalbahadoor",
    "Mehrotra Amit",
    "Dey Bapi",
    "Zimmerman Shawn",
    "Appala Subbarao",
    "Sarkar Avik Kumar",
    "Nadiminti Narayana",
    "Selvam Santhosh K",
    "Balakrishnan Uma",
    "Hunur Neha N",
    "Vadhera Puneet",
    "Jaiswal Rohit",
    "Hoake Michael",
    "Nacham Prabhakar",
    "Raicea Cristain",
    "Pradheep Rs",
    "stafford Jason",
    "Gupta Sachin",
    "Awasthi Akash",
    "Sheth Gunjan",
    "Monks Damien",
    "Lucas Stephen",
    "Palaniswami Rameshdurai",
    "BOTLA RAVI KIRAN KUMAR",
    "Bagade Vivek Kumar",
    "Deasy Brian",
    "Bingham Timothy",
    "Vaughn James",
    "Dhulipalla Anusha",
    "Stephen Lucas",
    "Bloomfield Stephen",
    "Mackay Scott",
    "Wagh Rakesh G",
    "Marthi Srinivasa Sharma",
    "Vandiver Christopher L",
    "Dwivedi Sourabh",
    "Philpot Vernon",
    "Casey Khan",
    "Moore Janice",
    "Mina Henin",
    "Kollavajjala Deepak",
    "Hazari naveen kumar",
    "Shivhare Jitendra",
    "Khurana Sumit",
    "Rajarathinam Senthilnathan",
]

DEFAULT_CUSTOMER_BANDS = [
    "EL1",
    "EL2",
    "EL3",
    "EL4",
    "EL5",
]

DEFAULT_CUSTOMER_HIRING_MANAGERS = [
    "Srinivasan Ramu",
    "KAZMIERCZAK PAUL",
    "Subbaraj Ravisankar",
    "Rajarathinam Senthil",
    "Aldentifier Christina",
    "Patil Natraj",
    "Mckinney Trey",
    "CHI SUN",
    "Makowski Joseph W",
    "Tyrell Krystal",
    "Chandra Vipin",
    "MACKAY SCOTT",
    "Janze Leonard",
    "Sharma Rishi",
    "BORCHELT PAUL",
    "Ramanathan Karthick",
    "Olstad Paul",
    "Kovvuri Lalbahadoor",
    "Mehrotra Amit",
    "Dey Bapi",
    "Zimmerman Shawn",
    "Appala Subbarao",
    "Sarkar Avik Kumar",
    "Nadiminti Narayana",
    "Selvam Santhosh K",
    "Balakrishnan Uma",
    "Hunur Neha N",
    "Vadhera Puneet",
    "Jaiswal Rohit",
    "Hoake Michael",
    "Nacham Prabhakar",
    "Anusha Dhulipalla",
    "Raicea Cristain",
    "Pradheep Rs",
    "stafford Jason",
    "Gupta Sachin",
    "Awasthi Akash",
    "Sheth Gunjan",
    "Monks Damien",
    "Lucas Stephen",
    "Palaniswami Rameshdurai",
    "Rohra Vinod",
    "BOTLA RAVI KIRAN KUMAR",
    "Bagade Vivek Kumar",
    "Deasy Brian",
    "Bingham Timothy",
    "Vaughn James",
    "Dhulipalla Anusha",
    "Stephen Lucas",
    "Bloomfield Stephen",
    "Mackay Scott",
    "Wagh Rakesh G",
    "Marthi Srinivasa Sharma",
    "Vandiver Christopher L",
    "Dwivedi Sourabh",
    "Philpot Vernon",
    "Casey Khan",
    "Moore Janice",
    "Mina Henin",
    "Kollavajjala Deepak",
    "Hazari naveen kumar",
    "Shivhare Jitendra",
    "Khurana Sumit",
    "Rajarathinam Senthilnathan",
]

DEFAULT_HCL_LEADERS = [
    "Bhaskar Motouru",
    "Himanshu Mohan",
    "Sridhar R",
    "Girish Kumar Joshi",
    "Sridhar R",
]

DEFAULT_HCL_DELIVER_SPOCS = [
    "Thrivikram Reddy C",
    "Karthik",
    "Sathish",
    "Dilip",
    "Dinesh",
    "Achit"
]
